In [1]:
import numpy as np


# Excersice 1

In [2]:
D_train = {((37.5,2),1),((36,1),0),((39,1),1),((37.5,1),0),((39,0),1),((37.5,0),0),((37.5,1),0),((36,2),1)}
D_test = {((36,0),0),((37.5,1),0),((39,1),1),((39,2),0)}

X_train = np.array([x for x,y in D_train])
Y_train = np.array([y for x,y in D_train]).reshape(-1,1)

X_test = np.array([x for x,y in D_test])
Y_test = np.array([y for x,y in D_test]).reshape(-1,1)

In [3]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier().fit(X_train,Y_train)

Y_pred = clf.predict(X_test)

print(Y_pred)

[1 0 1 0]


# Excersice 2

In [4]:
D_train = {((37.5,2),1),((36,1),0),((39,1),1),((37.5,1),0),((39,0),1),((37.5,0),0),((37.5,1),0),((36,2),1)}
D_test = {((36,0),0),((37.5,1),0),((39,1),1),((39,2),0)}

X_train = np.array([x for x,y in D_train])
Y_train = np.array([y for x,y in D_train]).reshape(-1,1)

X_test = np.array([x for x,y in D_test])
Y_test = np.array([y for x,y in D_test]).reshape(-1,1)

In [5]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier().fit(X_train,Y_train)

Y_pred = clf.predict(X_test)

print(Y_pred)

[1 0 1 0]


/var/folders/nd/w3ryxsr517x_r6n0pwltg2yw0000gn/T/ipykernel_54647/3482251619.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf = RandomForestClassifier().fit(X_train,Y_train)


In [6]:
from sklearn.metrics import accuracy_score, f1_score

print(accuracy_score(Y_test,Y_pred))
print(f1_score(Y_test,Y_pred))

0.75
0.6666666666666666


In [8]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10).fit(X_train,Y_train)

Y_pred = clf.predict(X_test)

print(Y_pred)
print(accuracy_score(Y_test,Y_pred))
print(f1_score(Y_test,Y_pred))

[1 0 1 0]
0.75
0.6666666666666666


/var/folders/nd/w3ryxsr517x_r6n0pwltg2yw0000gn/T/ipykernel_54647/3209394905.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf = RandomForestClassifier(n_estimators=10).fit(X_train,Y_train)


In [7]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=1000).fit(X_train,Y_train)

Y_pred = clf.predict(X_test)

print(Y_pred)
print(accuracy_score(Y_test,Y_pred))
print(f1_score(Y_test,Y_pred))

/var/folders/nd/w3ryxsr517x_r6n0pwltg2yw0000gn/T/ipykernel_54647/2448224143.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf = RandomForestClassifier(n_estimators=1000).fit(X_train,Y_train)


[1 0 1 0]
0.75
0.6666666666666666
