In [3]:
import numpy as np
from sklearn.cluster import KMeans

In [10]:
E = np.array([[8.5,16],[12.4,26.8],[9.3,21],[11.5,17],[17.5,25],[13,22.6],[4,16.5]])

kmeans = KMeans(n_clusters=2, init="k-means++").fit(E)
print(kmeans.labels_)
print(kmeans.cluster_centers_)
print(kmeans.inertia_)

[0 1 0 0 1 1 0]
[[ 8.325 17.625]
 [14.3   24.8  ]]
69.875


/Users/roman/Library/Python/3.9/lib/python/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [20]:
kmeans = KMeans(n_clusters=3, init="k-means++").fit(E)
print(kmeans.labels_)
print(kmeans.cluster_centers_)
print(kmeans.inertia_)

[2 0 2 2 0 0 1]
[[14.3        24.8       ]
 [ 4.         16.5       ]
 [ 9.76666667 18.        ]]
43.24666666666666


/Users/roman/Library/Python/3.9/lib/python/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
