In [3]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# Exercise 1

In [4]:
X = np.array([[16,22],[43,70],[135,50],[42,46],[60,59],[105,140]])
y = np.array([1,1,0,0,0,1])

logist_reg = LogisticRegression()
logist_reg.fit(X,y)

print(logist_reg.coef_)
print(logist_reg.intercept_)

[[-0.58628081  0.452637  ]]
[1.75862762]


# Exercise 2

In [23]:
from sklearn.preprocessing import PolynomialFeatures

X = np.array([[12,11],[13,14],[11,8],[6,2],[12,10],[7,11]])
y = np.array([0,1,1,0,0,0])

poly = PolynomialFeatures(degree=2,include_bias=False)
poly_X = poly.fit_transform(X)

logist_reg = LogisticRegression()
logist_reg.fit(poly_X,y)

print(logist_reg.coef_)
print(logist_reg.intercept_)

[[ 0.06417252 -0.20185234  0.38646318 -0.63534262  0.32988182]]
[-11.26416611]


# Exercise 3

In [21]:
X = np.array([[1,80],[20,3],[5,0],[13,12],[60,30],[10,40]])
y = np.array([2,2,1,1,3,3])


for i in range(1, len(set(y.flatten())) + 1):
    y_i = np.array([(1 if j == i else 0 )for j in y.flatten()])

    loist_reg = LogisticRegression()

    logist_reg.fit(X,y_i)

    thetas = [round(t, 3) for t in np.append(logist_reg.intercept_,logist_reg.coef_)]
    print(thetas)



[0 0 1 1 0 0]
[14.689, -0.789, -0.246]
[1 1 0 0 0 0]
[-0.917, -0.03, 0.024]
[0 0 0 0 1 1]
[-5.138, 0.196, 0.053]


# Exercsise 4

In [22]:
X = np.array([[0.3,0.3],[0.24,0.26],[0.33,0.2],[0.35,0.4],[0.39,0.38],[0.42,0.26]])
y = np.array([1,4,2,3,3,1])

poly = PolynomialFeatures(degree=2,include_bias=False)
poly_X = poly.fit_transform(X)

for i in range(1, len(set(y.flatten())) + 1):
    y_i = np.array([(1 if j == i else 0 )for j in y.flatten()])

    loist_reg = LogisticRegression()

    logist_reg.fit(poly_X,y_i)

    thetas = [round(t, 3) for t in np.append(logist_reg.intercept_,logist_reg.coef_)]
    print(thetas)

[-0.696, 0.043, -0.04, 0.03, -0.006, -0.032]
[-1.567, -0.008, -0.099, -0.009, -0.036, -0.055]
[-0.791, 0.062, 0.178, 0.038, 0.082, 0.113]
[-1.551, -0.098, -0.04, -0.06, -0.04, -0.027]
