In [9]:
%pip install -q scikit-learn numpy

You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model

# Exercise 1

In [28]:
# prepare data

X = np.array([[23,36],[23,34],[26,29],[21,40],[20,33],[25,35]])
y = np.array([0.1,0,1.2,-0.5,-1.5,0.7])

In [29]:

reg = linear_model.LinearRegression()
reg.fit(X,y)

print(reg.coef_)
print(reg.intercept_)

[0.44507793 0.04872847]
-11.917924528301889


# Exercise 2

In [30]:
# prepare data

X = np.array([[0.5,4.4],[1,4.0],[1.5,3.8],[1.6,3.7],[1.2,5.2],[0.7,4.3]])
y = np.array([6.8,8.1,9.3,11.1,11.6,13.6])
poly = PolynomialFeatures(degree=2,include_bias=False)
poly_X = poly.fit_transform(X)
print(poly_X)

[[ 0.5   4.4   0.25  2.2  19.36]
 [ 1.    4.    1.    4.   16.  ]
 [ 1.5   3.8   2.25  5.7  14.44]
 [ 1.6   3.7   2.56  5.92 13.69]
 [ 1.2   5.2   1.44  6.24 27.04]
 [ 0.7   4.3   0.49  3.01 18.49]]


In [31]:
reg = linear_model.LinearRegression()
reg.fit(poly_X,y)

print(reg.coef_)
print(reg.intercept_)

[1488.40846349  353.98329096 -180.84211164 -266.0540017    -3.9338903 ]
-1588.2412640756252


# Exercise 3

In [23]:
# prepare data

X = np.array([[17.5,20],[21.5,23],[19,19],[20,18],[22.5,16],[20.5,15]])
y = np.array([0.85,0.9,1.1,1,1.1,0.8])
poly = PolynomialFeatures(degree=2,include_bias=False)
poly_X = poly.fit_transform(X)
print(poly_X)


[[ 17.5   20.   306.25 350.   400.  ]
 [ 21.5   23.   462.25 494.5  529.  ]
 [ 19.    19.   361.   361.   361.  ]
 [ 20.    18.   400.   360.   324.  ]
 [ 22.5   16.   506.25 360.   256.  ]
 [ 20.5   15.   420.25 307.5  225.  ]]


In [24]:
reg = linear_model.Ridge(alpha=0.2)
reg.fit(poly_X,y)

print(reg.coef_)
print(reg.intercept_)

[-0.06191663  0.22686973 -0.00184305  0.00984303 -0.01145304]
-0.8999117645937594


# Exercise 4

In [26]:
# prepare data

X = np.array([[12,7],[10,8],[10,7.5],[15,5],[16,9],[18,8]])
y = np.array([5.5,6,7,6.5,7.5,10])

In [27]:
reg = linear_model.Ridge(alpha=0.1)
reg.fit(X,y)

print(reg.coef_)
print(reg.intercept_)

[0.34710592 0.36072884]
-0.2780020898709097
